In [2]:
%%capture
# STARTER CODE - RUN THIS CELL - DO NOT CHANGE
!pip install category_encoders
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import category_encoders as ce
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score, accuracy_score, recall_score, precision_score

In [3]:
# Load Data
df = pd.read_csv('seattle_weather_1948-2017.csv')

In [4]:
def RAIN_INSERTION(cols):
    """
    Impute False where NaN values are present
    """
    
    RAIN=cols[0]
    if pd.isnull(RAIN):
        return False
    else:
        return RAIN

def PRCP_INSERTION(col):
    """
    Insert the Mean of PRCP where NaN values are present
    """
    PRCP=col[0]
    if pd.isnull(PRCP):
        return df['PRCP'].mean()
    else:
        return PRCP

In [5]:
# Apply the Functions
df["RAIN"] = df[["RAIN"]].apply(RAIN_INSERTION, axis=1) # axis =1 means apply to columns 
df['PRCP']=df[['PRCP']].apply(PRCP_INSERTION,axis=1)

In [31]:
def heuristic(df):
    """
    Simple heuristic:
    
    If it rained the past two days then predict rain else predict no rain
    
    Frist two rows are predicted false be default
    """
    
    preds = []
    
    for x in range(len(df)):
        # If first two rows then predict false
        if x<2:
            preds.append(False)
        else:
            # If either of last two days == True then predict True
            if  (df.iloc[x-10]["PRCP"] >= 1.0):
                preds.append(True)
            else:
                preds.append(False)
    return preds

In [32]:
df["preds"] = heuristic(df)

In [33]:
# Determine Accuracy

# Create function to to find values

def calc_confuse(df):
 # Hold all possible values and set to zero
    FP = np.zeros(len(df))
    TP = np.zeros(len(df))
    FN = np.zeros(len(df))
    TN = np.zeros(len(df))
    
    for x in range(len(df)):
        
        # True Positive
        if (df["PRCP"].iloc[x] >= 1.0) & (df["preds"].iloc[x] == True):
            TP[x] = 1
        # True Negative
        elif (df["PRCP"].iloc[x] < 1.0) & (df["preds"].iloc[x] == False):
            TN[x] = 1
        # False Negative
        elif (df["PRCP"].iloc[x] >= 1.0) & (df["preds"].iloc[x] == False):
            FN[x] = 1
        # False Positive
        else:
            FP[x] = 1
    
    return FP, TP, FN, TN

In [34]:
# Extract results and create columns for each
w,x,y,z = calc_confuse(df)

df["FP"] = w
df["TP"] = x
df["FN"] = y
df["TN"] = z

# Look at 10 random rows to determin accuracy
df.sample(10)

             DATE  PRCP  TMAX  TMIN   RAIN  preds   FP   TP   FN   TN
9696   1974-07-19  0.00    71    57  False  False  0.0  0.0  0.0  1.0
14471  1987-08-15  0.00    66    55  False  False  0.0  0.0  0.0  1.0
1268   1951-06-22  0.00    76    48  False  False  0.0  0.0  0.0  1.0
6063   1964-08-07  0.00    76    59  False  False  0.0  0.0  0.0  1.0
19097  2000-04-14  0.14    52    46   True  False  0.0  0.0  0.0  1.0
638    1949-09-30  0.02    60    49   True  False  0.0  0.0  0.0  1.0
3655   1958-01-03  0.00    51    40  False  False  0.0  0.0  0.0  1.0
23252  2011-08-30  0.01    69    54   True  False  0.0  0.0  0.0  1.0
11146  1978-07-08  0.00    68    55  False  False  0.0  0.0  0.0  1.0
11502  1979-06-29  0.00    68    52  False  False  0.0  0.0  0.0  1.0

In [35]:
# Create a Mean Squared Error Function
def mse(y_true, y_pred):
    mse1=np.square(np.subtract(y_true,y_pred)).mean()
    return mse1

mse(y_test_r, y_pred_r)

27.249783291198238

In [36]:
# Your Mean Squared Error function should equal this value
mean_squared_error(y_test_r, y_pred_r)

27.249783291198234